### ISSUE TITLE
401 UNAUTHORIZED error

### ISSUE THREAD

**Issue by Dev-The-One-Reborn** [vovchic17/aiosend#1]
![Screenshot_2024-10-23_09-52-47](https://github.com/user-attachments/assets/fc41ba94-d363-4504-8459-e56bcd082882)

Throws unauthorized error even though the token is right. Copied your example for aiogram 3 from [here](https://aiocpa.readthedocs.io/en/latest/examples/aiogram3.html) but, as you can see, it doesn't work.

**Comment by vovchic17** [comment]
Are you using mainnet token?
Check this out
https://aiosend.readthedocs.io/en/latest/api/network.html#usage-example

**Comment by Dev-The-One-Reborn** [comment]
> Are you using mainnet token? Check this out https://aiocpa.readthedocs.io/en/latest/api/api_server.html#cryptopay.client.api_server.APIServer

That worked, thanks.
